A

diff --git a/.github/workflows/npm-publish.yml b/.github/workflows/npm-publish.yml
--- a/.github/workflows/npm-publish.yml
+++ b/.github/workflows/npm-publish.yml
@@ -27,19 +27,20 @@ jobs:
 
       - name: Update version 
         run: |- 
-          export $(npm info @hieudan26/demo version)
-          VERSION=$(npm info @hieudan26/demo version)
-          if [ $? -eq 1 ]
-          then
-            echo "SUCCESS"
-          else
-            echo "FAIL"
-          fi
+          checkExist=$(export $(npm info @hieudan26/demo version))
+          echo $checkExist
+          # VERSION=$(npm info @hieudan26/demo version)
+          # if [ $? -eq 1 ]
+          # then
+          #   echo "SUCCESS"
+          # else
+          #   echo "FAIL"
+          # fi
 
-          echo $VERSION
-          NEXTVERSION=$(echo ${VERSION} | awk -F. -v OFS=. '{$NF += 1 ; print}')
-          echo "$(jq --arg NEXTVERSION "$NEXTVERSION" '.version = $NEXTVERSION' ./package.json)" > package.json
-          cat ./package.json
+          # echo $VERSION
+          # NEXTVERSION=$(echo ${VERSION} | awk -F. -v OFS=. '{$NF += 1 ; print}')
+          # echo "$(jq --arg NEXTVERSION "$NEXTVERSION" '.version = $NEXTVERSION' ./package.json)" > package.json
+          # cat ./package.json
         working-directory: ./open-api
 
       - name: Publish package on NPM 📦   
